### ROTAS DE RESET PASSWORD
POST http://localhost:3334/auth/forgot-password
Content-Type: application/json

{
  "email": "matheusgomes110@hotmail.com"
}

###

POST http://localhost:3334/auth/verify-otp
Content-Type: application/json

{
  "email": "matheusgomes110@hotmail.com",
  "otp": "235982"
}

###

POST http://localhost:3334/auth/reset-password
Content-Type: application/json

{
  "email": "matheusgomes110@hotmail.com",
  "otp": "235982",
  "newPassword": "Mg?1234567"
}
